// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5XiLV8RjYWSdkzw4XUe9xAvGOpTiLVg',
    appId: '1:684089665977:web:4545159afd0fa9f8f8ae68',
    messagingSenderId: '684089665977',
    projectId: 'projet-flutter-7f5ad',
    authDomain: 'projet-flutter-7f5ad.firebaseapp.com',
    storageBucket: 'projet-flutter-7f5ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvKkXlVZgyFZGJMYGIQsqmbsBx9IZ3_0',
    appId: '1:684089665977:android:e59e19bef07e08fef8ae68',
    messagingSenderId: '684089665977',
    projectId: 'projet-flutter-7f5ad',
    storageBucket: 'projet-flutter-7f5ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UTm14ZeAXS4E5sjg2jxJjEppJhtXlRE',
    appId: '1:684089665977:ios:4e8d44e80b35e1a3f8ae68',
    messagingSenderId: '684089665977',
    projectId: 'projet-flutter-7f5ad',
    storageBucket: 'projet-flutter-7f5ad.appspot.com',
    iosClientId: '684089665977-79rih13fvnt78pl2oaitjj3n5ui3m7hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetProgrammationMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0UTm14ZeAXS4E5sjg2jxJjEppJhtXlRE',
    appId: '1:684089665977:ios:4e8d44e80b35e1a3f8ae68',
    messagingSenderId: '684089665977',
    projectId: 'projet-flutter-7f5ad',
    storageBucket: 'projet-flutter-7f5ad.appspot.com',
    iosClientId: '684089665977-79rih13fvnt78pl2oaitjj3n5ui3m7hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetProgrammationMobile',
  );
}
